### PR TITLE
Prevented rails from setting rails env to test when starting pool

### PR DESCRIPTION
**Pull request by charle692**

### CODE REVIEW

**Comment by charle692** [comment]
@caseyli @mtuck063 Don't merge this. It doesn't seem to work.

**Comment by mtuck063** [comment]
LGTM

**Review by mtuck063 — APPROVED** [review]

**Comment by charle692** [comment]
@caseyli @mtuck063 ok so this is ready to be reviewed again. I wanted to make some changes to it. If it's good, just let me know so that I can make a pr for internationalsafety.

**Comment by mtuck063** [comment]
LGTM

**Review by caseyli — APPROVED** [review]

**Pull request merged**
